### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nathanclevenger** [graphdl/admin#1]
- [ ] Generate Dynamic App
- [ ] Generate Dynamic Resources
- [ ] Support `_detail.columns`
- [ ] Support `_detail.lists`
- [ ] Generate Dynamic Filters
- [ ] Support Full Text Search
- [ ] Create Data Provider for db.mw
